application: pageshotpages
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
# - url: /favicon\.ico
#   static_files: icon.png
#   upload: icon\.png
#
# - url: /clipboard-8-xl\.png
#   static_files: clipboard-8-xl.png
#   upload: clipboard-8-xl\.png

#- url: /newpage\.html
#  static_files: newpage.html
#  upload: newpage\.html

# - url: /pageshot\.xpi
#   static_files: pageshot.xpi
#   upload: pageshot\.xpi
#
# - url: /pageshot\.update\.rdf
#   static_files: pageshot.update.rdf
#   upload: pageshot\.update\.rdf
#
# - url: /$
#   static_files: index.html
#   upload: index\.html
#
# - url: /pitch
#   static_files: pitch.html
#   upload: pitch\.html
#
# - url: /js
#   static_dir: js
#
# - url: /css
#   static_dir: css
#
# - url: /static
#   static_dir: static
#
# - url: /fontello-idea-fonts
#   static_dir: fontello-idea-fonts

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
